//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedStock.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedStock.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Line.
        /// </summary>
        public static string AddLine {
            get {
                return ResourceManager.GetString("AddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Inventory Management System - Hospital.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Categories.
        /// </summary>
        public static string Assigned_Categories {
            get {
                return ResourceManager.GetString("Assigned_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available_Categories.
        /// </summary>
        public static string Available_Categories {
            get {
                return ResourceManager.GetString("Available_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Code.
        /// </summary>
        public static string BatchCode {
            get {
                return ResourceManager.GetString("BatchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Min Stock.
        /// </summary>
        public static string BelowMinStock {
            get {
                return ResourceManager.GetString("BelowMinStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories_Title.
        /// </summary>
        public static string Categories_Title {
            get {
                return ResourceManager.GetString("Categories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Stock.
        /// </summary>
        public static string CurrentStock {
            get {
                return ResourceManager.GetString("CurrentStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department ID (Optional).
        /// </summary>
        public static string DepartmentId_Optional {
            get {
                return ResourceManager.GetString("DepartmentId_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpiryDate Optional.
        /// </summary>
        public static string ExpiryDate_Optional {
            get {
                return ResourceManager.GetString("ExpiryDate_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemCategories Title.
        /// </summary>
        public static string ItemCategories_Title {
            get {
                return ResourceManager.GetString("ItemCategories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ID.
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Title.
        /// </summary>
        public static string Items_Title {
            get {
                return ResourceManager.GetString("Items_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Stock.
        /// </summary>
        public static string MinStock {
            get {
                return ResourceManager.GetString("MinStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinStockAlerts Title.
        /// </summary>
        public static string MinStockAlerts_Title {
            get {
                return ResourceManager.GetString("MinStockAlerts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes (Optional).
        /// </summary>
        public static string Notes_Optional {
            get {
                return ResourceManager.GetString("Notes_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in..
        /// </summary>
        public static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Categories.
        /// </summary>
        public static string Open_Categories {
            get {
                return ResourceManager.GetString("Open_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ItemCategories.
        /// </summary>
        public static string Open_ItemCategories {
            get {
                return ResourceManager.GetString("Open_ItemCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Items.
        /// </summary>
        public static string Open_Items {
            get {
                return ResourceManager.GetString("Open_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open MinStockAlerts.
        /// </summary>
        public static string Open_MinStockAlerts {
            get {
                return ResourceManager.GetString("Open_MinStockAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Stock In.
        /// </summary>
        public static string Open_StockIn {
            get {
                return ResourceManager.GetString("Open_StockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Out.
        /// </summary>
        public static string Open_StockOut {
            get {
                return ResourceManager.GetString("Open_StockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation Out.
        /// </summary>
        public static string Reason_DonationOut {
            get {
                return ResourceManager.GetString("Reason_DonationOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Loss.
        /// </summary>
        public static string Reason_InvLoss {
            get {
                return ResourceManager.GetString("Reason_InvLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition Fulfill.
        /// </summary>
        public static string Reason_ReqFulfill {
            get {
                return ResourceManager.GetString("Reason_ReqFulfill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Off.
        /// </summary>
        public static string Reason_WriteOff {
            get {
                return ResourceManager.GetString("Reason_WriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Code.
        /// </summary>
        public static string ReasonCode {
            get {
                return ResourceManager.GetString("ReasonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Date.
        /// </summary>
        public static string ReceivedDate {
            get {
                return ResourceManager.GetString("ReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Line.
        /// </summary>
        public static string RemoveLine {
            get {
                return ResourceManager.GetString("RemoveLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition Detail ID (Optional).
        /// </summary>
        public static string RequisitionDetailId_Optional {
            get {
                return ResourceManager.GetString("RequisitionDetailId_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Item.
        /// </summary>
        public static string Select_Item {
            get {
                return ResourceManager.GetString("Select_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sku.
        /// </summary>
        public static string Sku {
            get {
                return ResourceManager.GetString("Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockIn Title.
        /// </summary>
        public static string StockIn_Title {
            get {
                return ResourceManager.GetString("StockIn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Out Management.
        /// </summary>
        public static string StockOut_Title {
            get {
                return ResourceManager.GetString("StockOut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost.
        /// </summary>
        public static string UnitCost {
            get {
                return ResourceManager.GetString("UnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
